# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sparsify": "neighbors.ipynb",
         "hstack": "neighbors.ipynb",
         "vstack": "neighbors.ipynb",
         "stack": "neighbors.ipynb",
         "NMSLibSklearnWrapper": "neighbors.ipynb",
         "FastJaccardNN": "neighbors.ipynb",
         "FastL2NN": "neighbors.ipynb",
         "FastKLDivNN": "neighbors.ipynb"}

modules = ["neighbors.py"]

doc_url = "https://AlanGanem.github.io/NMSLearn/nmslearn/"

git_url = "https://github.com/AlanGanem/nmslearn/tree/master/"

def custom_doc_links(name): return None
